### ISSUE TITLE
[FEATURE] Add custom HTTP error pages

### ISSUE THREAD

**Issue by Septem151** [Septem151/gifsync#10]
**What problem or issue is to be fixed?**
Currently there are no custom HTTP error pages, giving an unprofessional look when users encounter errors.

**Describe the solution you propose**
Add error pages for the following HTTP codes:
- 400 (Bad Request)
- 401 (Unauthorized)
- 404 (Not Found)
- 405 (Method Not Allowed)
- 429 (Too Many Requests)
- 500 (Internal Server Error)
- 503 (Service Unavailable) 

**Describe alternatives you've considered**
Templating should be used to create a generic error page, upon which the error code and message is passed into as parameters.

**Additional context**
None.

**Comment by Harry-Lees** [comment]
I created a pull request to add errors 400, 401, and 404. More can be added if needed.
