### ISSUE TITLE
[FEATURE] How to get gif url?

### ISSUE THREAD

**Issue by taprile314** [Septem151/gifsync#39]
I want to add the `synced-gif-url` as a browser source in OBS. Actually what i do is add the url `https://gifsync.herokuapp.com/show?gif_id=xxxx` as a browser source, then I interact with the source so I can click in accept spotify permissions and then I crop the source so only the gif is visible. 

This process is very tricky, is there a way to get the gif url and pass it to OBS directly? Maybe if I run the api locally i can get this done?

Thanks in advance!

**Comment by Septem151** [comment]
Hey there, this is actually exactly how I use the website currently as well. I create a Browser source, accept the Spotify permissions, set the transform to the boundaries of the gif, and set the background of the webpage source to transparent.

I realize it's not the best way to do things, but there's no other way to do this in the way GifSync Alpha is setup. The direct URL to gifs is indeed available as https://gifsync.herokuapp.com/api/me/synced-gif?gif_id=xxxx&song_id=xxxx if you right-click Open Image in new tab, however the gif will not auto-update to your music this way. The [/api/me/synced-gif](https://github.com/Septem151/gifsync/blob/master/gifsync/__init__.py#L207) route uses the song id from the URL params to return a newly created gif whose speed matches the song.

I'll keep this in mind as I'm working on the [GifSync Beta](https://github.com/Septem151/gifsync/milestone/1) but I'm pretty swamped with work and other projects at the moment, so progress is slow.
